---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: team-a
  namespace: team-a
spec:
  interval: 5m0s
  url: https://github.com/vincedesjardins/team-a
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: team-a
  namespace: team-a
spec:
  interval: 5m
  retryInterval: 30s
  timeout: 5m
  path: ./
  prune: true
  serviceAccountName: fluxcd
  sourceRef:
    kind: GitRepository
    name: team-a
