apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: beneva:hn:namespace-admin
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "watch", "list", "create", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: beneva:hn:namespace-admin
subjects:
- kind: ServiceAccount
  name: fluxcd
  namespace: team-a
roleRef:
  kind: ClusterRole
  name: beneva:hn:namespace-admin
  apiGroup: rbac.authorization.k8s.io
