apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: enforce-team-label
spec:
  validationFailureAction: enforce
  background: false
  rules:
  - name: enforce-team-label
    match:
      any:
      - resources:
          kinds:
          - Namespace
    context:
    - name: namespace
      apiCall:
        urlPath: "/api/v1/namespaces/{{serviceAccountNamespace}}"
    exclude:
      any:
      - clusterRoles:
        - cluster-admin
    preconditions:
      all:
      - key: "{{ namespace.metadata.labels.root }}"
        operator: Equals
        value: "true"
    validate:
      message: >-
        Wrong values for namespace labels
      deny:
        conditions:
          any:
          - key: "{{ request.object.metadata.labels.team }}"
            operator: Equals
            value: "{{ namespace.metadata.labels.team }}"
            message: "team label should be {{ namespace.metadata.labels.team }}"
          - key: "{{ request.object.metadata.labels.parent }}"
            operator: Equals
            value: "{{ namespace.metadata.name }}"
            message: "parent label should be {{ namespace.metadata.name }}"
          - key: "{{ request.object.metadata.labels.root }}"
            operator: Equals
            value: "false"
            message: "root label should be false"
