apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: enforce-team-label
spec:
  validationFailureAction: enforce
  background: false
  rules:
  - name: enforce-team-label
    match:
      any:
      - resources:
          kinds:
          - Namespace
    context:
    - name: namespace
      apiCall:
        urlPath: "/api/v1/namespaces/{{serviceAccountNamespace}}"
    exclude:
      any:
      - clusterRoles:
        - cluster-admin
    preconditions:
      all:
      - key: "{{ namespace.metadata.labels.root }}"
        operator: Equals
        value: "true"
      - key: "{{ namespace.metadata.labels }}"
        operator: AnyIn
        value:
        - team
        - parent
        - root
        - istio.io/rev
    validate:
      message: "Namespace label `team` must have value `{{  namespace.metadata.labels.team }}` and `parent` label must have value {{ namespace.metadata.name }} and label `root` must have value `false`."
      pattern:
        metadata:
          labels:
            team: "{{ namespace.metadata.labels.team }}"
            parent: "{{ namespace.metadata.name }}"
            root: "false"
