apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: enforce-team-label
spec:
  validationFailureAction: enforce
  background: false
  rules:
  - name: enforce-team-label
    match:
      any:
      - resources:
          kinds:
          - Namespace
    context:
    - name: namespace
      apiCall:
        urlPath: "/api/v1/namespaces/{{serviceAccountNamespace}}"
    exclude:
      any:
      - clusterRoles:
        - cluster-admin
    preconditions:
      all:
      - key: "{{ namespace.metadata.labels.root }}"
        operator: Equals
        value: "true"
      - key: "{{ request.object.metadata.labels }}"
        operator: NotIn
        value: "root"
    validate:
      message: "Namespace label `team` with value `{{ request.object.metadata.labels.team }}` must match parent namespace `team` label having value `{{ namespace.metadata.name }}`."
      pattern:
        metadata:
          labels:
            team: "{{ namespace.metadata.labels.team }}"
            parent: "{{ namespace.metadata.name }}"
